<?php

namespace Maurobonucci\Laravel_Magnifinance\Providers;

use Illuminate\Support\ServiceProvider;

Class MagnifinanceServiceProvider extends ServiceProvider
{

    public function boot()
    {

    }

    public function register()
    {
        //parent::register(); // TODO: Change the autogenerated stub
    }
}
